### ISSUE TITLE
Éric Vyncke's IESG review

### ISSUE THREAD

**Issue by thomas-fossati** [tlswg/dtls-conn-id#103]
https://mailarchive.ietf.org/arch/msg/tls/R4Sh7CkbadK9bLCHzmfyGHKthqg/

```
-- Abstract --
As an important part of this document is the padding, should it be mentioned
also in the abstract ?

-- Section 3 --
While I am not a DTLS expert, I find this section quite difficult to understand
the reasoning behind the specification as little explanations are given about,
e.g, what is the motivation of "A zero-length value indicates that the server
will send with the client's CID but does not wish the client to include a CID."

-- Section 6 --
I am puzzled by the text:
     "There is a strategy for ensuring that the new peer address is able
      to receive and process DTLS records.  No such strategy is defined
      in this specification."
Does this mean that there is no way to update the peer IP address ?

== NITS ==

-- Section 1 --
Please expand CID on first use outside of the abstract.

-- Section 4 --
Suggest to add a short paragraph as a preamble to figure 3. Currently, it looks
like figure 3 belongs to the 'zeros' field description.
```

**Update from Éric re: Section 6**
```
Re-reading the end of the section 6 gives indeed some insights on the
overall process, which I failed to understand at first reading. May I
suggest to complement the last bullet as "defined in this specification
but relies on the application using DTLS" ?
```

**Comment by boaks** [comment]
About "-- Section 3 --, DTLS / zero-length CID"

[RFC5246 - 7.4.1.4.  Hello Extensions](https://tools.ietf.org/html/rfc5246#section-7.4.1.4)

"An extension type MUST NOT appear in the ServerHello unless the same
 extension type appeared in the corresponding ClientHello."

The "zero-length CID" therefore is mainly used for the very common cases, where only the clients are required to send such a CID, but not the server. 

Maybe adding a hint to RFC5246 7.4.1.4 will help?

**Comment by boaks** [comment]
About "-- Section 6 --"

Yes, that's still very complex:

First, processing the record seems to be easier (less restricted), than use a changed source address for sending data back.

Using a changed source address for sending data back to, is not generally solved. 

There are some special case, e.g., if the data sent back is very small, there is no risk (at least, none has explained one). There may also be some upper-layer mechanisms, which helps out (e.g. [draft-ietf-core-echo-request-tag](https://tools.ietf.org/wg/core/draft-ietf-core-echo-request-tag) for coap).
 
And there is a idea of a general solution [dtls-rrc](https://datatracker.ietf.org/doc/draft-tschofenig-tls-dtls-rrc), but that will require more time. Because of the required time, the idea was to release this spec without RRC and postpone that general work (see also issue #80).

**Comment by kaduk** [comment]
> As an important part of this document is the padding, should it be mentioned
also in the abstract ?

Some initial attempt at this in #120
